### ISSUE TITLE
Flowing async contexts

### ISSUE THREAD

**Issue by rogeralsing** [clearctvm/zipkin.net#3]
Would you be open to merge support for flowing async context?

We have an internal wrapper that enables this for one of the other C# Zipkin libraries.
This allows us to do the same kind of `using` blocks as you do here, but instead of passing around the spans and client etc. it's all ambient, much like `TransactionScope` works.

It uses LogicalCallContext/AsyncLocal under the hood.

Or do you prefer to have a more explicit API where all the different elements are passed around manually?

Our API looks like this, all the span state etc is handled by the async context.
https://github.com/rogeralsing/ElasticTraceLogging/blob/master/Demo/Program.cs#L37
(Although that public repo is very dated)

**Comment by hammett** [comment]
Hi, we also use AsyncLocal https://github.com/clearctvm/zipkin.net/blob/master/src/Zipkin/TraceContextPropagation.cs

And the API usage ends up very similar to the one you use.

**Comment by rogeralsing** [comment]
Awesome! thanks for the quick answer, I'll take this for a spin then and see if we can use it to replace ours
