### ISSUE TITLE
Help Requested: When to use StartClientTrace

### ISSUE THREAD

**Issue by jjathman** [clearctvm/zipkin.net#7]
I am adding zipkin.net to a web service but I'm a little confused as to when to use certain aspects of the API.

I have a controller that I would like to instrument, my initial thought was to use the StartServerTrace, but it looks like if the client calling this server hadn't already started a trace then creating a new server trace does nothing? Since it would take us some time to be able to migrate everything to using Zipkin, I was hoping for some kind of API where if a trace was already running it would add to the existing trace, but if nothing was started then it would start a new trace. I'm just a little confused how to accomplish this. Thanks for any guidance.

**Comment by hammett** [comment]
How's the client starting a trace? Is it a web service calling another web service?

**Comment by jjathman** [comment]
Yep, I would have webservice A calling webservice B. WS B is what I am instrumenting with zipkin.net, so ideally I would have service A start the trace, but it's possible there will be other clients of B who haven't been set up to use Zipkin yet, but I would still like to get as much info from B as possible even in the cases where a trace wasn't started prior to calling B.

**Here are my two scenarios**
1. A starts trace, calls B. B joins existing trace
1. C doesn't start a trace, calls B. B starts a new trace since one wasn't already in progress

Hope this makes sense. Thanks!

**Comment by hammett** [comment]
In this case use StartClientOrContinueTrace
https://github.com/clearctvm/zipkin.net/blob/master/src/Zipkin/Tracers/StartClientOrContinueTrace.cs

-- but for scenario 1, have some filter in B that calls
StartServerTrace if the right headers were passed along by A.

On Mon, May 8, 2017 at 12:47 PM, Joe Athman <notifications@github.com> wrote:
> Yep, I would have webservice A calling webservice B. WS B is what I am
> instrumenting with zipkin.net, so ideally I would have service A start the
> trace, but it's possible there will be other clients of B who haven't been
> set up to use Zipkin yet, but I would still like to get as much info from B
> as possible even in the cases where a trace wasn't started prior to calling
> B.
>
> Here are my two scenarios
>
> A starts trace, calls B. B joins existing trace
> C doesn't start a trace, calls B. B starts a new trace since one wasn't
> already in progress
>
> Hope this makes sense. Thanks!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Cheers,
hammett
http://www.d-collab.com/
http://www.hammettblog.com/

**Comment by jjathman** [comment]
Do you have some example code of how to use TraceContextPropagation to that StartClientOrContinueTrace functions correctly? I assume I'm supposed to use TraceContextPropagation somehow to get the context ready so the constructor for StartClientOrContinueTrace works correctly, but I'm not sure I understand it correctly.

**Comment by hammett** [comment]
https://github.com/clearctvm/zipkin.net/blob/master/sample/ApiUsage/Program.cs and some test cases IIRC

**Comment by jjathman** [comment]
In that example program it starts a new trace before it puts the dictionary in to the propagate method. If I follow this pattern with StartClientOrContinueTrace won't it always start a new trace because it doesn't have any way to know there is already a trace in progress?

**Comment by hammett** [comment]
Like I said above "-- but for scenario 1, have some filter in B that calls
StartServerTrace if the right headers were passed along by A."

**Comment by jjathman** [comment]
Sorry! Github had all of that hidden as quoted text by default so I didn't see that part of your response. Thanks.
